### ISSUE TITLE
TO-DO • Bugfixes

### ISSUE THREAD

**Issue by lucasliet** [lucasliet/ads_aula04#1]
tudo na página de [Lista de Filmes](https://github.com/lucasliet/pipoca-filmes/blob/cf00854f132d05e28ba83863b504741ec7539ef5/WebContent/FilmesLista.jsp)
- [x] botão de voltar pro topo da página
- [x] mudar o table-light pra table-striped
https://github.com/lucasliet/pipoca-filmes/blob/cf00854f132d05e28ba83863b504741ec7539ef5/WebContent/FilmesLista.jsp#L48
- [x] tirar o .js do fontawesome sendo importado na lista pra arrumar o bug do table-striped, não estamos usando ele nessa página de qualquer jeito
https://github.com/lucasliet/pipoca-filmes/blob/cf00854f132d05e28ba83863b504741ec7539ef5/WebContent/FilmesLista.jsp#L20
- [x] mudar o form de GET para POST
https://github.com/lucasliet/pipoca-filmes/blob/cf00854f132d05e28ba83863b504741ec7539ef5/WebContent/FilmesLista.jsp#L32
